//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLCITAPREVIA
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> FECHAREALIZADA { get; set; }
        public Nullable<System.DateTime> FECHAFIJADA { get; set; }
        public string CLIENTE { get; set; }
        public int ATENDIDA { get; set; }
    
        public virtual TBLCLIENTES TBLCLIENTES { get; set; }
    }
}
