//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLMASCOTAS
    {
        public int IDMASCOTA { get; set; }
        public string NOMBRE { get; set; }
        public string RAZA { get; set; }
        public Nullable<System.DateTime> FECHANACIMIENTO { get; set; }
        public string PROPIETARIO { get; set; }
    
        public virtual TBLCLIENTES TBLCLIENTES { get; set; }
    }
}
