//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLRECETAS
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public Nullable<int> MASCOTA { get; set; }
        public Nullable<float> COSTETOTAL { get; set; }
    
        public virtual TBLMASCOTAS TBLMASCOTAS { get; set; }
    }
}
